### ISSUE TITLE
water portal delete

### ISSUE THREAD

**Issue by xion87** [MassiveCraft/CreativeGates#66] opened 2013-11-13 00:39 UTC
When i destroy a water portal,  all water will come out....  is possible when i do it, to clean all water in portal? Thank you

**Comment by ulumulu1510** [comment] 2016-03-21 10:03
Might still be valid, yet we have never experienced this issue ourselfs.

**Comment by morfie78** [comment] 2016-03-21 19:59
This is kind of related to #113 .  Same thing I wrote there applies here.
I'd classify this as a nice to have, but it would be really nice to have.  Not that I have a problem cleaning up the water every time, but when there are other portals nearby, the water joins with them as well and everything becomes a big mess.
If you'd like a demonstration, I can link to you my server privately (so as not to advertise here :) )

**Comment by ulumulu1510** [comment] 2016-03-22 08:06
The issue is being processed.

**Comment by ulumulu1510** [comment] 2016-03-22 09:17
Issue fixed in the upcomming version

**Closed by ulumulu1510** 2016-03-22 09:17 UTC
Labels: Bug
