### ISSUE TITLE
Breaking water portals in the nether produces water

### ISSUE THREAD

**Issue by ThatBum** [MassiveCraft/CreativeGates#113] opened 2015-10-07 03:05 UTC
I take it this isn't intended behavior. It can be used to farm obsidian. Recommend having the water evaporate like other water in the nether.

**Comment by ulumulu1510** [comment] 2016-03-21 10:18
When you break a plugin by hand, the water disappears. To recreate this, I would need to know how your players destroy those gates.

**Comment by morfie78** [comment] 2016-03-21 19:54
This happens on our server too.  We'd LOOOOVE it if this didn't happen.  How we currently handle it is by charging a high price (IGM) for an admin to light a nether portal, then threatening to tempban people who misuse the portal for its water.

To answer @ulumulu1510 , just standard creation.  We place our portal activator block (iron block) somewhere in the frame, make the frame, light the portal, water appears and everyone is happy.  Breaking the portal happens via pickaxe, etc.   Portal goes boom, water spills out.  Usually one water source block per every 2x2 square in the portal.  For example, a 2 wide by 3 high portal (that is the area the water occupies) will have 1 source block on the bottom, 1 source block one y higher (usually staggered), and the 1 more source block one y higher (also staggered):

XXXX
XAWX
XWAX
XAWX

X= Frame
A= Air
W= Water Source Block

**Comment by ThatBum** [comment] 2016-03-21 22:23
Indeed, I dunno if it's interacting with another plugin or what, but it's definitely happening. It's in all dimensions, not just the Nether, but the Nether is the most problematic. All one has to do is break a block anywhere in the frame, there's an explosion, and the water turns into normal water source blocks. We have glowstone configured as the activator block.

I noticed there's a pull request titled "Portal water bug correction." Could this be a fix that was forgotten about?

**Comment by ulumulu1510** [comment] 2016-03-22 07:49
If so it'd be very nice ^^ I am currently very busy, but I can test this solution really quick later the day and see what happens.

**Comment by ulumulu1510** [comment] 2016-03-22 08:06
The issue is being processed.

**Comment by ulumulu1510** [comment] 2016-03-22 09:17
Issue fixed in the upcomming version

**Closed by ulumulu1510** 2016-03-22 09:17 UTC
Labels: Bug
