### ISSUE TITLE
The portal going side way.

### ISSUE THREAD

**Issue by luong8000** [MassiveCraft/CreativeGates#109] opened 2015-06-27 01:13 UTC
The portal going side ways when I create one with a watch. It make it side ways. Not the portal frame the something in the frame.

**Comment by meoso** [comment] 2015-06-30 12:45
This is a duplicate of issue [#100](https://github.com/MassiveCraft/CreativeGates/issues/100) which has been fixed in source code; however, the build has not been uploaded to spigot/bukkit.

Please read the issue thread for a manual fix (via worldedit).

**Comment by oloflarsson** [comment] 2015-07-15 15:26
Fixed.

**Closed by oloflarsson** 2015-07-15 15:26 UTC
