### ISSUE TITLE
Naming / Access issue

### ISSUE THREAD

**Issue by ArchieIrving** [MassiveCraft/CreativeGates#140] opened 2018-07-10 01:53 UTC
- **Affected Plugin Name:** CreativeGates
- **Affected Plugin Version:** 2.1.4.0

## Describe your Environment

- **Server Version:** Spigot 1.11.2

## Steps to Reproduce this Bug
1. One person creates a gate called X
2. Another person creates a different gate also called X
3. These gates are now linked together even though separate people created them.

## Observed Results
If one person creates two portals, with the name 'home' as an example. Then another person creates two portals, also with the name 'home' these four portals will now be linked together so you can walk through them all. This also continues to be an issue if even more players create portals with the name 'home'.

## Expected Results
I would expect;
1. The players' portals only link to the portals they create.
(or)
2. They would have to choose a different name than one that's already been taken.

**Comment by shmith** [comment] 2018-08-17 23:12
This is not a bug and is always how CreativeGates has functioned. On the MassiveCraft server (the home of these plugins) all gates, regardless of owner, can be linked. That is why players are told to make unique portal codes, rather than generic ones like "home".

This has always how it has functioned and how it has been intended to function.

**Comment by TheComputerGeek2** [comment] 2018-08-18 20:08
Closing
Not a bug, very much an intended feature.

**Closed as completed by TheComputerGeek2** 2018-08-18 20:08 UTC

**Comment by ArchieIrving** [comment] 2018-09-03 04:33
Oh, alrighty then. Seems like a weird interaction but okay.
