### ISSUE TITLE
Directional Issues

### ISSUE THREAD

**Issue by MrWiik** [MassiveCraft/CreativeGates#105] opened 2015-04-03 07:58 UTC
when you make a portal facing east or west the portal gets placed the wrong way

**Comment by meoso** [comment] 2015-04-06 12:52
@MrWiik , 
duplicate of [issue #100](https://github.com/MassiveCraft/CreativeGates/issues/100) which is fixed in source-code, but not yet released.

**Closed** 2015-04-09 14:53 UTC
